-- EXCLUINDO REGISTROS DAS TABELAS

SELECT * FROM PRODUTOS

DELETE FROM PRODUTOS WHERE VALOR_UNITARIO = 0.00; -- DELETANDO PELO PREÇO DO PRODUTO

DELETE FROM PRODUTOS WHERE ID_PRODUTO = 11; -- DELETANDO PELO ID

DELETE FROM PRODUTOS WHERE ID_PRODUTO IN (11, 12, 13); -- DELETANDO NA CLAUSULA IN ()