-- COMANDO SELECT É USADO PARA SELECIONAR AS INFORMAÇOES DAS TABELAS
-- PODEMOS UTILIZAR O SELECT * QUE IRÁ LISTAR TODOS OS CAMPOS
-- PODEMOS UTILIZAR O SELECT + NOME_CAMPO QUE IRÁ LSITAR SOMENTE OS CAMPOS ESPECIFICOS

SELECT * FROM TIPO_TELEFONE

SELECT DESCRICAO FROM TIPO_TELEFONE

SELECT * FROM TIPO_ENDERECO

SELECT DESCRICAO FROM TIPO_ENDERECO

SELECT * FROM TELEFONES

SELECT DDD, TELEFONE FROM TELEFONES

SELECT * FROM CLIENTES

SELECT * FROM PRODUTOS

SELECT * FROM PEDIDOS

SELECT ID_PEDIDO, DATA_PEDIDO, VALOR_TOTAL FROM PEDIDOS