-- CONSULTA UTILIZANDO INNER JOIN

-- CONSULTANDO CLEIENTES, TELEFONE E ENDEREÇO
SELECT 
	* 
FROM CLIENTES CL (NOLOCK)
	INNER JOIN TELEFONES TE (NOLOCK) ON (TE.ID_CLIENTE = CL.ID_CLIENTE)
	INNER JOIN TIPO_TELEFONE TI (NOLOCK) ON (TI.ID_TIPO_TELEFONE = TE.ID_TIPO_TELEFONE)
WHERE CL.ID_CLIENTE = 1
	AND TI.DESCRICAO = 'CELULAR'

-- OBTENDO SÓ OS CAMPOS NECESSÁRIOS
SELECT 
	CL.ID_CLIENTE,
	CL.NOME,
	CL.TIPO_PESSOA,
	TE.DDD,
	TE.TELEFONE,
	TI.DESCRICAO AS TIPO_TELEFONE
FROM CLIENTES CL (NOLOCK)
	INNER JOIN TELEFONES TE (NOLOCK) ON (TE.ID_CLIENTE = CL.ID_CLIENTE)
	INNER JOIN TIPO_TELEFONE TI (NOLOCK) ON (TI.ID_TIPO_TELEFONE = TE.ID_TIPO_TELEFONE)

-- ORDENANDO A CONSULTA
SELECT 
	CL.ID_CLIENTE,
	CL.NOME,
	CL.TIPO_PESSOA,
	TE.DDD,
	TE.TELEFONE,
	TI.DESCRICAO AS TIPO_TELEFONE
FROM CLIENTES CL (NOLOCK)
	INNER JOIN TELEFONES TE (NOLOCK) ON (TE.ID_CLIENTE = CL.ID_CLIENTE)
	INNER JOIN TIPO_TELEFONE TI (NOLOCK) ON (TI.ID_TIPO_TELEFONE = TE.ID_TIPO_TELEFONE)
ORDER BY CL.NOME

-- CONSULTANDO COM INNER JOIN E WHERE
SELECT 
	CL.ID_CLIENTE,
	CL.NOME,
	CL.TIPO_PESSOA,
	TE.DDD,
	TE.TELEFONE,
	TI.DESCRICAO AS TIPO_TELEFONE
FROM CLIENTES CL (NOLOCK)
	INNER JOIN TELEFONES TE (NOLOCK) ON (TE.ID_CLIENTE = CL.ID_CLIENTE)
	INNER JOIN TIPO_TELEFONE TI (NOLOCK) ON (TI.ID_TIPO_TELEFONE = TE.ID_TIPO_TELEFONE)
WHERE TI.DESCRICAO = 'CELULAR'
ORDER BY CL.NOME

SELECT 
	CL.ID_CLIENTE,
	CL.NOME,
	CL.TIPO_PESSOA,
	TE.DDD,
	TE.TELEFONE,
	TI.DESCRICAO AS TIPO_TELEFONE
FROM CLIENTES CL (NOLOCK)
	INNER JOIN TELEFONES TE (NOLOCK) ON (TE.ID_CLIENTE = CL.ID_CLIENTE)
	INNER JOIN TIPO_TELEFONE TI (NOLOCK) ON (TI.ID_TIPO_TELEFONE = TE.ID_TIPO_TELEFONE)
WHERE TI.ID_TIPO_TELEFONE = 1 AND CL.TIPO_PESSOA = 'F'
ORDER BY CL.NOME