-- CONSULTA DE DADOS UTILIZANDO SUB-SELECTS

-- SELECT SIMPLES DOS CLIENTES

SELECT 
	CL.ID_CLIENTE,
	CL.NOME,
	CL.TIPO_PESSOA
FROM CLIENTES CL (NOLOCK)

---------------------------------------------------------------------------------------

-- UTILIZANDO UM SUB SELECT
SELECT 
	CL.ID_CLIENTE,
	CL.NOME,
	CL.TIPO_PESSOA,
	(SELECT COUNT(*) FROM PEDIDOS PED(NOLOCK) WHERE PED.ID_CLIENTE = CL.ID_CLIENTE) AS QTD_PEDIDOS
FROM CLIENTES CL (NOLOCK)

---------------------------------------------------------------------------------------

-- UTILIZANDO UM SUB SELECT (neste caso melhor usar o inner para não fazer 2 sub selects)

-- ESTE PRIMEIRO EXEMPLO NÃO É MUITO INDICADO QUANDO EXISTEM MUITOS REGISTROS EM UMA TABELA
SELECT 
	PED.ID_PEDIDO,
	(SELECT PRO.DESCRICAO FROM PRODUTOS PRO (NOLOCK) WHERE PRO.ID_PRODUTO = PED.ID_PRODUTO) AS DESCRICAO,
	(SELECT PRO.VALOR_UNITARIO FROM PRODUTOS PRO (NOLOCK) WHERE PRO.ID_PRODUTO = PED.ID_PRODUTO) AS VALOR_UNITARIO,
	PED.QUANTIDADE,
	PED.VALOR_TOTAL
FROM PEDIDOS PED (NOLOCK)

-- AQUI, UM EXEMPLO MELHOR OTMIZADO UTILIZANDO O INNER JOIN
SELECT
	PED.ID_PEDIDO,
	PRO.DESCRICAO,
	PRO.VALOR_UNITARIO,
	PED.QUANTIDADE,
	PED.VALOR_TOTAL
FROM PEDIDOS PED (NOLOCK)
INNER JOIN PRODUTOS PRO (NOLOCK) ON (PRO.ID_PRODUTO = PED.ID_PRODUTO)