-- FUNÇOÕES NATIVAS DO SQL SERVER PARTE 2

-- COUNT -> CONTAGEM
SELECT 
	PRO.DESCRICAO,
	COUNT(*) QT_VENDAS
FROM PEDIDOS PED (NOLOCK)
	INNER JOIN PRODUTOS PRO (NOLOCK) ON (PRO.ID_PRODUTO = PED.ID_PRODUTO)
	INNER JOIN CLIENTES CL (NOLOCK) ON (CL.ID_CLIENTE = PED.ID_CLIENTE)
GROUP BY PRO.DESCRICAO

-------------------------------------------------------------------------------

-- HAVING -> CONTAGEM DE VALORES AGRUPADOS
SELECT
	PRO.DESCRICAO,
	COUNT(*) QT_VENDAS
FROM PEDIDOS PED (NOLOCK)
	INNER JOIN PRODUTOS PRO (NOLOCK) ON (PRO.ID_PRODUTO = PED.ID_PRODUTO)
	INNER JOIN CLIENTES CL (NOLOCK) ON (CL.ID_CLIENTE = PED.ID_CLIENTE)
GROUP BY PRO.DESCRICAO
HAVING COUNT(*) > 6

-------------------------------------------------------------------------------

-- CASE WHEN
SELECT
	PRO.DESCRICAO,
	PRO.VALOR_UNITARIO,
CASE
	WHEN PRO.VALOR_UNITARIO BETWEEN 1 AND 10 THEN 'BARATO'
	WHEN PRO.VALOR_UNITARIO BETWEEN 11 AND 100 THEN 'NA MÉDIA'
	ELSE 'CARO'
END CATEGORIA_PRECO
FROM PRODUTOS PRO (NOLOCK)

-------------------------------------------------------------------------------

-- ISNULL

SELECT
	PED.ID_PEDIDO,
	PED.QUANTIDADE
FROM PEDIDOS PED (NOLOCK)
	INNER JOIN PRODUTOS PRO (NOLOCK) ON (PRO.ID_PRODUTO = PED.ID_PRODUTO)

SELECT
	ISNULL(PED.ID_PEDIDO, 0) AS ID_PEDIDO,
	ISNULL(PED.QUANTIDADE, 0) AS QUANTIDADE
FROM PEDIDOS PED (NOLOCK)
	RIGHT JOIN PRODUTOS PRO (NOLOCK) ON (PRO.ID_PRODUTO = PED.ID_PRODUTO)
