-- FUNÇÕES NATIVAS DO SQL PARTE 03

-- COMANDO TOP UTILIZADO PARA LISTAR UMA DETERMINADA QUANTIDADE DE REGISTROS
SELECT * FROM PEDIDOS

-- COM O COMANDO TOP, LISTAREMOS APENAS O 10 PRMEIROS REGISTROS
SELECT TOP 7 * FROM PEDIDOS

-- COM O COMANTO TOP N PERCENT, LISTAREMOS UM PERCENTUAL DE REGISTROS DA TABELA
SELECT TOP 50 PERCENT * FROM PEDIDOS

-- O COMANDO REPLACE É UTILIZADO PARA SUBSTITUIRMOS ALGUM CARACTERE EM NOSSOS DADOS
SELECT
	PRO.ID_PRODUTO,
	PRO.DESCRICAO,
	PRO.VALOR_UNITARIO
FROM PRODUTOS PRO (NOLOCK)

-- IREMOS SUBSTITUIR O Ç (CEDILHA) POR C SEM CEDILHA
SELECT
	PRO.ID_PRODUTO,
	REPLACE(PRO.DESCRICAO, 'Ç', 'C') AS DESCRICAO,
	PRO.VALOR_UNITARIO
FROM PRODUTOS PRO (NOLOCK)

-- IREMOS ADICIONAR OS ACENTOS
SELECT
	PRO.ID_PRODUTO,
	REPLACE(PRO.DESCRICAO, 'E', 'É') AS DESCRICAO,
	PRO.VALOR_UNITARIO
FROM PRODUTOS PRO (NOLOCK)

-- PODEMOS SUSBISTITUIR TUDO DE UMA VEZ INSERINDO REPLACE DENTRO DE REPLACE
SELECT
	PRO.ID_PRODUTO,
	REPLACE(
		REPLACE(DESCRICAO, 'É', 'E'), 'Ç', 'C') AS DESCRICAO,
	VALOR_UNITARIO	
FROM PRODUTOS PRO (NOLOCK)

-- O COMANDO REPLICATE É UTILIZADO PARA REPETIR UMA STRING UM DETERMINADO NUMERO DE VEZES
SELECT 
	PRO.ID_PRODUTO,
	PRO.DESCRICAO
FROM PRODUTOS PRO (NOLOCK)

-- INSERINDO ZEROS A ESQUERDA
SELECT 
	CONCAT(REPLICATE('0', 4 - LEN(PRO.ID_PRODUTO)), PRO.ID_PRODUTO) AS ID_PRODUTO,
	PRO.DESCRICAO
FROM PRODUTOS PRO (NOLOCK)