-- FUNÇÕES NATIVAS DO SQL SERVER

SELECT * FROM CLIENTES
-----------------------------------------------------------------------------

-- UPPER CONVERTE CARACTERES PARA LETRA MAIUSCULA

SELECT
	CL.ID_CLIENTE,
	UPPER(CL.NOME) AS NOME,
	CL.TIPO_PESSOA,
	CL.DOCUMENTO 
FROM CLIENTES CL (NOLOCK)

-----------------------------------------------------------------------------

-- LOWER CONVERTE CARACTERES PARA LETRA MINUSCULA

SELECT
	CL.ID_CLIENTE,
	LOWER(CL.NOME) AS NOME,
	CL.TIPO_PESSOA,
	CL.DOCUMENTO 
FROM CLIENTES CL (NOLOCK)

-----------------------------------------------------------------------------

-- ROUND REALIZA O AREDONDAMENTO DE VALORES E NUMEROS

SELECT ROUND(245.145,2) AS VALOR

SELECT 
	PRO.DESCRICAO, 
	PRO.VALOR_UNITARIO, 
	ROUND(PRO.VALOR_UNITARIO * 12.5 / 100,2) AS DESCONTO 
FROM PRODUTOS PRO (NOLOCK)