-- FUNÇÕES NATIVAS DO SQL SERVER

-- CAST: CONVERTE UM TIPO DE DADOS PARA OUTRO TIPO DE DADOS
SELECT * FROM PRODUTOS

SELECT
	PRO.ID_PRODUTO,
	PRO.DESCRICAO,
	PRO.VALOR_UNITARIO
FROM PRODUTOS PRO (NOLOCK)

-- SE TENTAR FAZER ASSIM TEREMOS UM ERRO:
SELECT
	PRO.ID_PRODUTO,
	PRO.DESCRICAO,
	PRO.VALOR_UNITARIO,
	PRO.DESCRICAO + ' - ' + VALOR_UNITARIO AS PRODUTO_PRECO
FROM PRODUTOS PRO (NOLOCK)

-- PRECISAMOS USAR O CAST
SELECT
	PRO.ID_PRODUTO,
	PRO.DESCRICAO,
	PRO.VALOR_UNITARIO,
	PRO.DESCRICAO + ' - ' + CAST(VALOR_UNITARIO AS VARCHAR) AS PRODUTO_PRECO
FROM PRODUTOS PRO (NOLOCK)

-------------------------------------------------------------------------------------------------

-- CONVERT: CONVERTE UMA EXPRESSÃO PARA UM DETERMINADO TIPO
SELECT * FROM PEDIDOS

SELECT
	PED.ID_PEDIDO,
	CONVERT(VARCHAR, PED.DATA_PEDIDO, 103) AS DATA_PEDIDO
FROM PEDIDOS PED (NOLOCK)

-- FORMATO INTERESSATE PARA FORMATAR DATAS:
SELECT
	PED.ID_PEDIDO,
	CONVERT(VARCHAR(11), PED.DATA_PEDIDO, 113) AS DATA_PEDIDO
FROM PEDIDOS PED (NOLOCK)

-- AQUI, PODEMOS VER MAIS CÓDIGOS DE FORMATAÇÃO DE DATAS
-- https://learn.microsoft.com/pt-br/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver16

-------------------------------------------------------------------------------------------------

-- SET DATEFORMAT: DETERMINA COMO SÃO INTERPRETADOS OS VALORES DE DATA

SET DATEFORMAT YDM -- ANO/DIA/MES
SET DATEFORMAT DMY -- DIA/MES/ANO
SET DATEFORMAT YMD -- ANO/MES/DIA

SELECT 
	PED.ID_PEDIDO,
	PED.DATA_PEDIDO
FROM PEDIDOS PED (NOLOCK)

SELECT 
	PED.ID_PEDIDO,
	PED.DATA_PEDIDO
FROM PEDIDOS PED (NOLOCK)
WHERE DATA_PEDIDO BETWEEN '2023-01-05 14:05:00.000' AND '2023-01-05 18:05:00.000'