-- FUNÇÕES NATIVAS DO SQL SERVER

-- O COMANDO LIKE SERVE PARA PESQUISARMOS UM DETERMINADO VALOR DENTRO DE UM CAMPO

-- LIKE '% XY %'
-- DESSA FORMA O COMANDO IRÁ BUSCAR TUDO QUE POSSUI OS CARACTERES DENTRO DO CAMPO
SELECT * FROM PRODUTOS PRO(NOLOCK) WHERE PRO.DESCRICAO LIKE '%ET%'

---------------------------------------------------------------------------------------

-- LIKE '% XY'
-- DESTA FORMA O COMANDO IRÁ BUSCAR TUDO QUE TERMINA COM OS CARACTERES DENTRO DA STRING
SELECT * FROM PRODUTOS PRO(NOLOCK) WHERE PRO.DESCRICAO LIKE '%TA'

---------------------------------------------------------------------------------------

-- LIKE 'XY %'
-- DESTA FORMA O COMANDO IRÁ BUSCAR TUDO QUE INICIA COM OS CARACTERES DENTRO DA STRING
SELECT * FROM PRODUTOS PRO(NOLOCK) WHERE PRO.DESCRICAO LIKE 'CA%'

---------------------------------------------------------------------------------------

-- O COMANDO TRUNCATE É UTILIZADO PARA TRUNCAR (APAGAR TUDO) QUE ESTÁ EM UMA TABELA
-- VAMOS CRIAR UMA TABELA DE EXEMPLO CHAMADA: PRODUTOS_TESTE E INSERIR OS REGISTROS DA TABELA PRODUTO

SELECT
	PRO.ID_PRODUTO,
	PRO.DESCRICAO,
	PRO.VALOR_UNITARIO
	INTO PRODUTO_TESTE -- ESTA SINTAXE PERMITE CRIAR UMA TABELA DIRETAMENTE ATRAVÉS DE UMA CONSULTA
FROM PRODUTOS PRO(NOLOCK)

SELECT * FROM PRODUTO_TESTE -- TABELA DE TESTES CRIADA NO BLOCO ACIMA

-- TRUNCATE LIMPA TODA A TABELA, INDEPENDENTE DA QUANTIDADE DE REGISTROS QUE A MESMA TIVER
TRUNCATE TABLE PRODUTO_TESTE -- OBS.: NUNCA UTILIZAR ESTE COMANDO EM PRODUÇÃO

DROP TABLE PRODUTO_TESTE
