-- FUNÇÕES NATIVAS DA LINGUAGEM SQL

-- RELEMBRANDO O QUE TEMOS NA TABELA DE PEDIDOS
SELECT * FROM PEDIDOS

-- SUM -> SOMA
SELECT SUM(VALOR_TOTAL) AS VALOR_TOTAL
FROM PEDIDOS

--AVG AVAREGE -> MÉDIA
SELECT AVG(VALOR_TOTAL) AS MEDIA
FROM PEDIDOS

-- MIN -> MINIMO
SELECT MIN(VALOR_TOTAL) AS MINIMO
FROM PEDIDOS

-- MAX -> MAXIMO
SELECT MAX(VALOR_TOTAL) AS MAXIMO
FROM PEDIDOS

------------------------------------------------------------------------------
-- % -> REPRESENTA O MODULO DA DIVISÃO
SELECT
	ID_PEDIDO,
	QUANTIDADE,
	QUANTIDADE % 2 AS MODULO
FROM PEDIDOS

-- SQRT -> REPRESENTA A RAIZ QUADRADA
SELECT
	ID_PEDIDO,
	QUANTIDADE,
	SQRT(QUANTIDADE) AS RAIZ_QUADRADA
FROM PEDIDOS

-------------------------------------------------------------------------------

-- GROUP BY -> AGRUPAMENTO
SELECT 
	PRO.DESCRICAO,
	SUM(PED.QUANTIDADE) AS TOTAL_QTD,
	SUM(PED.VALOR_TOTAL) AS VALOR_TOTAL
FROM PEDIDOS PED (NOLOCK)
	INNER JOIN PRODUTOS PRO (NOLOCK) ON (PRO.ID_PRODUTO = PED.ID_PRODUTO)
	INNER JOIN CLIENTES CL (NOLOCK) ON (CL.ID_CLIENTE = PED.ID_CLIENTE)
GROUP BY PRO.DESCRICAO