-- OPERADORES ARITIMETICOS NO SQL

SELECT
	PED.ID_PEDIDO,
	PED.ID_CLIENTE,
	PED.ID_PRODUTO,
	PED.DATA_PEDIDO,
	PED.QUANTIDADE,
	PRO.VALOR_UNITARIO,

	-- OPERADOR DE MULTIPLICAÇÃO
	PED.QUANTIDADE * PRO.VALOR_UNITARIO AS VALOR_TOTAL_PEDIDO,

	-- OPERADOR DE DIVISÃO
	PRO.VALOR_UNITARIO / 2 AS PRECO_COMPRA,

	-- PERCENTUAL
	15 * PRO.VALOR_UNITARIO / 100 AS PERCENTUAL,

	-- ADIÇÃO
	PRO.VALOR_UNITARIO + (15 * PRO.VALOR_UNITARIO / 100) AS NOVA_MARGEM_LUCRO,

	-- SUBTRAÇÃO
	PRO.VALOR_UNITARIO - (15 * PRO.VALOR_UNITARIO / 100) AS NOVA_MARGEM_DESCONTO

FROM PEDIDOS PED (NOLOCK)
	INNER JOIN PRODUTOS PRO (NOLOCK) ON (PRO.ID_PRODUTO = PED.ID_PRODUTO)