/*INSERINDO REGISTROS NA TABELA TIPO_ENDERECO*/
INSERT INTO TIPO_ENDERECO (DESCRICAO) VALUES ('RESIDENCIAL');
INSERT INTO TIPO_ENDERECO (DESCRICAO) VALUES ('COMERCIAL');

/*INSERINDO REGISTROS NA TABELA TIPO_TELEFONE*/
INSERT INTO TIPO_TELEFONE (DESCRICAO) VALUES ('RESIDENCIAL');
INSERT INTO TIPO_TELEFONE (DESCRICAO) VALUES ('COMERCIAL');
INSERT INTO TIPO_TELEFONE (DESCRICAO) VALUES ('CELULAR');

/*INSERINDO REGISTROS NA TABELA PRODUTOS*/
INSERT INTO PRODUTOS (DESCRICAO, VALOR_UNITARIO) VALUES ('CAMISETA', 20.00);
INSERT INTO PRODUTOS (DESCRICAO, VALOR_UNITARIO) VALUES ('BERMUDA', 30.00);
INSERT INTO PRODUTOS (DESCRICAO, VALOR_UNITARIO) VALUES ('CALÇA MOLETON', 40.00);
INSERT INTO PRODUTOS (DESCRICAO, VALOR_UNITARIO) VALUES ('CALÇA JEANS', 50.00);
INSERT INTO PRODUTOS (DESCRICAO, VALOR_UNITARIO) VALUES ('CAMISA POLO', 35.00);
INSERT INTO PRODUTOS (DESCRICAO, VALOR_UNITARIO) VALUES ('CAMISA SOCIAL', 60.00);
INSERT INTO PRODUTOS (DESCRICAO, VALOR_UNITARIO) VALUES ('MEIA', 8.00);
INSERT INTO PRODUTOS (DESCRICAO, VALOR_UNITARIO) VALUES ('GRAVATA', 22.00);
INSERT INTO PRODUTOS (DESCRICAO, VALOR_UNITARIO) VALUES ('TERNO', 100.00);
INSERT INTO PRODUTOS (DESCRICAO, VALOR_UNITARIO) VALUES ('CHAPEU', 27.00);
INSERT INTO PRODUTOS (DESCRICAO, VALOR_UNITARIO) VALUES ('BANANA', 0.00);
INSERT INTO PRODUTOS (DESCRICAO, VALOR_UNITARIO) VALUES ('ABACATE', 0.00);
INSERT INTO PRODUTOS (DESCRICAO, VALOR_UNITARIO) VALUES ('MELANCIA', 0.00);

/*INSERINDO REGISTROS NA TABELA CLIENTES*/
INSERT INTO CLIENTES (NOME, TIPO_PESSOA, DOCUMENTO) VALUES ('JOAQUIN DA SILVA','F','123456789')
INSERT INTO CLIENTES (NOME, TIPO_PESSOA, DOCUMENTO) VALUES ('JOÃO DA SILVA','F','987654321')
INSERT INTO CLIENTES (NOME, TIPO_PESSOA, DOCUMENTO) VALUES ('MARIA DA GRAÇA','F','1258745632')
INSERT INTO CLIENTES (NOME, TIPO_PESSOA, DOCUMENTO) VALUES ('NERD DOS DADOS','J','12552445222')
INSERT INTO CLIENTES (NOME, TIPO_PESSOA, DOCUMENTO) VALUES ('','','')
