--PODEMOS REALIZAR A CONVERSÃO DE DATAS DE DUAS MANEIRAS, SEJA UTILIZANDO O COMANDO CAST OU CONVERT

SELECT 
ID_PEDIDO,
DATA_PEDIDO,
DATA_ENTREGA
FROM PEDIDOS



--UTILIZANDO O CAST
SELECT 
ID_PEDIDO,
CAST(DATA_PEDIDO AS DATE) AS DATA_PEDIDO,
CAST(DATA_ENTREGA AS DATETIME) AS DATA_ENTREGA,
CAST(DATA_PEDIDO AS VARCHAR) AS DATA_PEDIDO --REPARE QUE NESSE CAMPO ELE IRÁ ASSUMIR UM PADRÃO NATIVO DO SQL
FROM PEDIDOS

--UTILIZANDO O CONVERT
SELECT 
ID_PEDIDO,
CONVERT(VARCHAR(12),DATA_PEDIDO,103) AS DATA_PEDIDO,
CONVERT(VARCHAR(12),DATA_PEDIDO,104) AS DATA_PEDIDO,
CONVERT(VARCHAR(12),DATA_PEDIDO,105) AS DATA_PEDIDO,
CONVERT(VARCHAR(12),DATA_PEDIDO,106) AS DATA_PEDIDO,
CONVERT(VARCHAR(12),DATA_PEDIDO,107) AS DATA_PEDIDO,
CONVERT(VARCHAR(12),DATA_PEDIDO,108) AS DATA_PEDIDO,
CONVERT(VARCHAR(12),DATA_PEDIDO,109) AS DATA_PEDIDO,
CONVERT(VARCHAR(12),DATA_PEDIDO,110) AS DATA_PEDIDO,
CONVERT(VARCHAR(12),DATA_PEDIDO,111) AS DATA_PEDIDO,
CONVERT(VARCHAR(12),DATA_PEDIDO,112) AS DATA_PEDIDO
FROM PEDIDOS


--PODEMOS TAMBÉM EXTRAIR INFORMAÇÕES DAS DATAS COMO O ANO, MES E DIA
SELECT 
ID_PEDIDO,
DATA_PEDIDO,
YEAR(DATA_PEDIDO) AS ANO_PEDIDO,
MONTH(DATA_PEDIDO) AS MES_PEDIDO,
DAY(DATA_PEDIDO) AS DIA_PEDIDO
FROM PEDIDOS


--PODEMOS TAMBÉM UTILIZAR A FUNÇÃO DATENAME PARA OBETER O NOME DO MÊS
SELECT 
ID_PEDIDO,
DATA_PEDIDO,
DATENAME(MONTH,DATA_PEDIDO) AS MES_PEDIDO
FROM PEDIDOS



--PODEMOS TAMBÉM FAZER CALCULOS COM DATA
SELECT 
A.ID_PEDIDO,
A.DATA_PEDIDO,
A.DATA_ENTREGA,
B.NOME AS CLIENTE,
C.DESCRICAO AS PRODUTO,
C.VALOR_UNITARIO,
A.QUANTIDADE,
A.VALOR_TOTAL AS TOTAL_PEDIDO
FROM PEDIDOS A(NOLOCK)
INNER JOIN CLIENTES B(NOLOCK) ON (B.ID_CLIENTE = A.ID_CLIENTE)
INNER JOIN PRODUTOS C(NOLOCK) ON (C.ID_PRODUTO=A.ID_PRODUTO)


--FAZENDO CALCULOS COM DATAS
SELECT 
A.ID_PEDIDO,
A.DATA_PEDIDO,
A.DATA_ENTREGA,
DATEDIFF(DD,A.DATA_PEDIDO,A.DATA_ENTREGA) AS DIAS_PEDIDO_ENTREGA,
DATEDIFF(DD,A.DATA_PEDIDO,GETDATE()) AS DIAS_PEDIDO_ATE_HOJE,
DATEDIFF(MM,A.DATA_PEDIDO,A.DATA_ENTREGA) AS MESES_PEDIDO_ENTREGA,
DATEDIFF(MM,A.DATA_PEDIDO,GETDATE()) AS MESES_PEDIDO_ATE_HOJE,

DATEADD(DAY, 10, A.DATA_PEDIDO) AS DEZ_DIAS_APOS_PEDIDO,
DATEADD(DAY, 40, A.DATA_PEDIDO) AS QUARENTA_DIAS_APOS_PEDIDO,
DATEADD(MONTH, 3, A.DATA_PEDIDO) AS TRES_MESES_APOS_PEDIDO,

B.NOME AS CLIENTE,
C.DESCRICAO AS PRODUTO,
C.VALOR_UNITARIO,
A.QUANTIDADE,
A.VALOR_TOTAL AS TOTAL_PEDIDO
FROM PEDIDOS A(NOLOCK)
INNER JOIN CLIENTES B(NOLOCK) ON (B.ID_CLIENTE = A.ID_CLIENTE)
INNER JOIN PRODUTOS C(NOLOCK) ON (C.ID_PRODUTO=A.ID_PRODUTO)


--FUNCAO NATIVA EOMONTH EXIBE O ULTIMO DIA DO MÊS DE UMA DETERMINADA DATA
SELECT '2023-01-05'

SELECT EOMONTH('2023-01-05')

SELECT 
A.ID_PEDIDO,
A.DATA_PEDIDO,
EOMONTH(A.DATA_PEDIDO) AS ULTIMO_DIA_MES
FROM PEDIDOS A(NOLOCK)