--PODEMOS REALIZAR CONCATENAÇÃO (JUNÇÃO) DE DADOS E STRING

--DEVEMOS SEMPRE NOS ATENTARMOS AOS TIPOS DE DADOS DOS CAMPOS QUE QUEREMOS UNIFICAR/JUNTAR/CONCATENAR
--NESSE EXEMPLO IRÁ DAR ERRO...
SELECT 
ID_PEDIDO,
DATA_PEDIDO,
DATENAME(MONTH,DATA_PEDIDO) AS MES_PEDIDO,
DATENAME(MONTH,DATA_PEDIDO) + '-' + YEAR(DATA_PEDIDO) AS PERIODO_PEDIDO
FROM PEDIDOS


--FORMA CORRETA
SELECT 
ID_PEDIDO,
DATA_PEDIDO,
DATENAME(MONTH,DATA_PEDIDO) AS MES_PEDIDO,
DATENAME(MONTH,DATA_PEDIDO) + ' - ' + CAST(YEAR(DATA_PEDIDO) AS VARCHAR) AS PERIODO_PEDIDO
FROM PEDIDOS




--UM OUTRO EXEMPLO PARA CONCATENARMOS
SELECT
ID_PRODUTO,
DESCRICAO,
VALOR_UNITARIO
FROM PRODUTOS


SELECT 
ID_PRODUTO,
DESCRICAO,
VALOR_UNITARIO,
'Promoção: ' + DESCRICAO + ' - ' + CAST(VALOR_UNITARIO AS VARCHAR) AS OFERTAS
FROM PRODUTOS


--E VAMOS JUNTAR ALGUMAS COISAS QUE APRENDEMOS ANTERIORMENTE E APLICAR UM DESCONTO PARA ESSAS OFERTAS
SELECT 
ID_PRODUTO,
DESCRICAO,
VALOR_UNITARIO,
'10%' AS PERCENTUAL_DESCONTO,
VALOR_UNITARIO * 10/100 AS VALOR_DESCONTO,
VALOR_UNITARIO - (VALOR_UNITARIO * 10/100) AS VALOR_COM_DESCONTO,
'Promoção: ' + DESCRICAO + ' - ' + CAST(CAST(VALOR_UNITARIO - (VALOR_UNITARIO * 10/100) AS NUMERIC(18,2)) AS VARCHAR)  AS OFERTAS
FROM PRODUTOS