--ROW NUMBER SERVE PARA ENUMERAR SEQUENCIALMENTE UMA CONSULTA QUE REALIZAMOS
SELECT * FROM PEDIDOS


SELECT 
ROW_NUMBER() OVER(ORDER BY DATA_PEDIDO ASC) AS SEQUENCIA,
DATA_PEDIDO,
QUANTIDADE,
VALOR_TOTAL
FROM PEDIDOS



SELECT
ID_CLIENTE,
DATA_PEDIDO,
VALOR_TOTAL
FROM PEDIDOS
ORDER BY ID_CLIENTE



SELECT 
ID_CLIENTE,

ROW_NUMBER() OVER(PARTITION BY ID_CLIENTE ORDER BY ID_CLIENTE) AS SEQUENCIA,
DATA_PEDIDO,
QUANTIDADE,
VALOR_TOTAL
FROM PEDIDOS