--INICIALMENTE IREMOS IMPORTAR NOSSA PLANILHA

--EM SEGUIDA VAMOS CONSULTAR A PLANILHA IMPORTADA
SELECT * FROM PRODUTOS$

SELECT * FROM PRODUTOS


--AGORA PODEMOS INSERIR NA TABELAS OFICIAL PRODUTOS OS ITENS IMPORTADOS
INSERT INTO PRODUTOS
SELECT * FROM PRODUTOS$



SELECT * FROM PRODUTOS

