--CRIANDO UMA VIEW PARA VISUALIZAR TODOS PRODUTOS
CREATE VIEW VW_TODOS_PRODUTOS
AS
SELECT * FROM PRODUTOS
GO

SELECT * FROM VW_TODOS_PRODUTOS


--CRIANDO UMA VIEW COM CONDIÇÃO PARA LISTAR PRODUTOS COM VALOR MAIOR OU IGUAL A 30,00
CREATE VIEW VW_PRODUTOS_CAROS
AS
SELECT * FROM PRODUTOS 
WHERE VALOR_UNITARIO >= 30
GO

SELECT * FROM VW_PRODUTOS_CAROS


--CRIANDO UMA VIEW PARA VISUALIZAR OS PEDIDOS REALIZADOS
CREATE VIEW VW_PEDIDOS AS 
SELECT 
A.ID_PEDIDO,
CAST(A.DATA_PEDIDO AS DATE) AS DATA_PEDIDO,
UPPER(B.NOME) AS NOME_CLIENTE,
C.DESCRICAO AS PRODUTO,
C.VALOR_UNITARIO,
A.QUANTIDADE,
A.VALOR_TOTAL
FROM PEDIDOS A(NOLOCK)
INNER JOIN CLIENTES B(NOLOCK) ON (B.ID_CLIENTE = A.ID_CLIENTE)
INNER JOIN PRODUTOS C(NOLOCK) ON (C.ID_PRODUTO=A.ID_PRODUTO)
GO

SELECT * FROM VW_PEDIDOS