--EXCLUINDO UMA VIEW
CREATE VIEW VW_PRODUTOS_CAROSSS
AS
SELECT * FROM PRODUTOS 
WHERE VALOR_UNITARIO >= 20
GO


SELECT * FROM VW_PRODUTOS_CAROSSS

--PARA EXCLUIRMOS UMA VIEW SIMPLESMENTE UTILIZAMOS O COMANDO DROP + O NOME DA VIEW
DROP VIEW VW_PRODUTOS_CAROSSS