--CRIANDO UMA FUNCAO SIMPLES SEM PARAMETRO (POUCO UTILIZADO NO MERCADO DE TRABALHO)
CREATE FUNCTION dbo.CalculaDescontoFixo()
RETURNS NUMERIC(18,2)
AS
BEGIN
    DECLARE @VALOR_COM_DESCONTO		NUMERIC(18,2)	

	SELECT @VALOR_COM_DESCONTO = A.VALOR_UNITARIO - (A.VALOR_UNITARIO * 10 / 100)
	FROM PRODUTOS A(NOLOCK)    
	    
	RETURN @VALOR_COM_DESCONTO
END


select dbo.CalculaDescontoFixo()



--CRIANDO UMA FUNCAO QUE RETORNA UMA TABELA SIMPLES SEM PARAMETRO (POUCO UTILIZADO NO MERCADO DE TRABALHO)
CREATE FUNCTION dbo.CalculaDescontoFixoTodosProdutos()
RETURNS TABLE
AS
RETURN
(
    SELECT 
	A.ID_PRODUTO,
	A.DESCRICAO,
	A.VALOR_UNITARIO,
	'10%' AS PERCENTUAL_DESCONTO,
	CAST(A.VALOR_UNITARIO - (A.VALOR_UNITARIO * 10 / 100) AS NUMERIC(18,2)) AS VALOR_COM_DESCONTO
	FROM PRODUTOS A(NOLOCK)
);


 select * from dbo.CalculaDescontoFixoTodosProdutos()