--CRIANDO UMA FUNÇÃO SIMPLES
CREATE FUNCTION dbo.CalculaDesconto(@ID_PRODUTO INTEGER, @DESCONTO NUMERIC(12,2))
RETURNS NUMERIC(18,2)
AS
BEGIN
    DECLARE @VALOR_COM_DESCONTO		NUMERIC(18,2)	

	SELECT @VALOR_COM_DESCONTO = A.VALOR_UNITARIO - (A.VALOR_UNITARIO * @DESCONTO / 100)
	FROM PRODUTOS A(NOLOCK)    
	WHERE A.ID_PRODUTO = @ID_PRODUTO
    
	RETURN @VALOR_COM_DESCONTO
END


SELECT * FROM PRODUTOS

SELECT dbo.CalculaDesconto(9,50)



--CRIANDO UMA FUNÇÃO COM RETORNO DE TABELA
CREATE FUNCTION dbo.CalculaDescontoTodosProdutos (@DESCONTO NUMERIC(18,2))
RETURNS TABLE
AS
RETURN
(
    SELECT 
	A.ID_PRODUTO,
	A.DESCRICAO,
	A.VALOR_UNITARIO,
	CAST(@DESCONTO AS VARCHAR) + '%' AS PERCENTUAL_DESCONTO,
	CAST(A.VALOR_UNITARIO - (A.VALOR_UNITARIO * @DESCONTO / 100) AS NUMERIC(18,2)) AS VALOR_COM_DESCONTO
	FROM PRODUTOS A(NOLOCK)
);


--VISUALIZANDO A FUNÇÃO
SELECT * FROM dbo.CalculaDescontoTodosProdutos(70)


--CRIANDO UMA FUNÇÃO COM RETORNO DE TABELA PARA RETORNAR UM ITEM ESPECIFICO
CREATE FUNCTION dbo.CalculaDescontoProdutoEspecifico (@ID_PRODUTO	INTEGER,@DESCONTO NUMERIC(18,2))
RETURNS TABLE
AS
RETURN
(
    SELECT 
	A.ID_PRODUTO,
	A.DESCRICAO,
	A.VALOR_UNITARIO,
	CAST(@DESCONTO AS VARCHAR) + '%' AS PERCENTUAL_DESCONTO,
	CAST(A.VALOR_UNITARIO - (A.VALOR_UNITARIO * @DESCONTO / 100) AS NUMERIC(18,2)) AS VALOR_COM_DESCONTO
	FROM PRODUTOS A(NOLOCK)
	WHERE A.ID_PRODUTO = @ID_PRODUTO
);



--VISUALIZANDO A FUNÇÃO
SELECT * FROM dbo.CalculaDescontoProdutoEspecifico(10,40)




--CRIANDO UMA FUNÇÃO SIMPLES POREM MUITO UTILIZADA
CREATE FUNCTION dbo.Desconto(@VALOR NUMERIC(18,2), @DESCONTO NUMERIC(12,2))
RETURNS NUMERIC(18,2)
AS
BEGIN
    DECLARE @VALOR_COM_DESCONTO		NUMERIC(18,2)	

	SELECT @VALOR_COM_DESCONTO = @VALOR - (@VALOR * @DESCONTO / 100)	
    
	RETURN @VALOR_COM_DESCONTO
END


--UTILIZANDO A FUNÇÃO
SELECT 
A.ID_PRODUTO,
A.DESCRICAO,
A.VALOR_UNITARIO,
(SELECT dbo.Desconto(A.VALOR_UNITARIO, 30)) AS VALOR_COM_DESCONTO
FROM PRODUTOS A(NOLOCK)



--CRIANDO UMA FUNÇÃO PARA REMOVER ACENTOS
CREATE FUNCTION dbo.RemoveAcentos(@String	VARCHAR(MAX))
RETURNS VARCHAR(MAX)
AS
BEGIN
	--RETIRA ACENTOS DAS VOGAIS
	SET @String = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(@String,'á','a'),'à','a'),'â','a'),'ã','a'),'ä','a')
    SET @String = REPLACE(REPLACE(REPLACE(REPLACE(@String,'é','e'),'è','e'),'ê','e'),'ë','e')
    SET @String = REPLACE(REPLACE(REPLACE(REPLACE(@String,'í','i'),'ì','i'),'î','i'),'ï','i')
    SET @String = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(@String,'ó','o'),'ò','o'),'ô','o'),'õ','o'),'ö','o')
    SET @String = REPLACE(REPLACE(REPLACE(REPLACE(@String,'ú','u'),'ù','u'),'û','u'),'ü','u')
    
    --RETIRA ACENTOS DAS CONSOANTES
    SET @String = REPLACE(@String,'ý','y')
    SET @String = REPLACE(@String,'ñ','n')
    SET @String = REPLACE(@String,'ç','c')
    
    RETURN UPPER(@String)

END

--VISUALIZANDO OS ACENTOS
SELECT
ID_PRODUTO,
DESCRICAO
FROM PRODUTOS


--UTILIZANDO A FUNCAO PARA REMOVER ACENTO
SELECT
ID_PRODUTO,
dbo.RemoveAcentos(DESCRICAO) AS DESCRICAO
FROM PRODUTOS




--CRIANDO UMA FUNÇÃO PARA FORMATAR O CPF/CNPJ DO CLIENTE
SELECT * FROM CLIENTES


CREATE FUNCTION dbo.FormataCPF(@DOCUMENTO VARCHAR(14), @TIPO_PESSOA VARCHAR(01))
RETURNS VARCHAR(20)
AS
BEGIN
	
	DECLARE @RETORNO VARCHAR(20)
	
	IF @TIPO_PESSOA = 'F'   ---233-255-288-09
		BEGIN			
			SET @RETORNO = SUBSTRING(@DOCUMENTO,1,3) + '-' + SUBSTRING(@DOCUMENTO,4,3) + '-' + SUBSTRING(@DOCUMENTO,7,3) + '-' + SUBSTRING(@DOCUMENTO,10,2)							
		END	
	ELSE	
		BEGIN
			SET @RETORNO = SUBSTRING(@DOCUMENTO,1,2) + '.' + SUBSTRING(@DOCUMENTO,3,3) + '.' + SUBSTRING(@DOCUMENTO,6,3) + '/' + SUBSTRING(@DOCUMENTO,9,4) + '-' + SUBSTRING(@DOCUMENTO,12,2)				
		END	--						25.575.633/0001-01
	

RETURN @RETORNO
END





SELECT
ID_CLIENTE,
NOME,
dbo.FormataCPF(DOCUMENTO,TIPO_PESSOA) AS CPF_CNPJ
FROM CLIENTES
