--ALTERANDO UMA FUNCAO
CREATE FUNCTION dbo.CalculaDesconto(@DESCONTO NUMERIC(12,2))
RETURNS NUMERIC(18,2)
AS
BEGIN
    DECLARE @VALOR_COM_DESCONTO		NUMERIC(18,2)	

	SELECT @VALOR_COM_DESCONTO = A.VALOR_UNITARIO - (A.VALOR_UNITARIO * @DESCONTO / 100)
	FROM PRODUTOS A(NOLOCK)    
	
    
	RETURN @VALOR_COM_DESCONTO
END
GO




ALTER FUNCTION dbo.CalculaDesconto(@ID_PRODUTO INTEGER, @DESCONTO NUMERIC(12,2))
RETURNS NUMERIC(18,2)
AS
BEGIN
    DECLARE @VALOR_COM_DESCONTO		NUMERIC(18,2)	

	SELECT @VALOR_COM_DESCONTO = A.VALOR_UNITARIO - (A.VALOR_UNITARIO * @DESCONTO / 100)
	FROM PRODUTOS A(NOLOCK)    
	WHERE A.ID_PRODUTO = @ID_PRODUTO
    
	RETURN @VALOR_COM_DESCONTO
END
GO



ALTER FUNCTION dbo.FormataCPF(@DOCUMENTO VARCHAR(14), @TIPO_PESSOA VARCHAR(01))
RETURNS VARCHAR(20)
AS
BEGIN
	
	DECLARE @RETORNO VARCHAR(20)
	
	IF @TIPO_PESSOA = 'F'   ---233-255-288-09
		BEGIN			
			SET @RETORNO = SUBSTRING(@DOCUMENTO,1,3) + '.' + SUBSTRING(@DOCUMENTO,4,3) + '.' + SUBSTRING(@DOCUMENTO,7,3) + '-' + SUBSTRING(@DOCUMENTO,10,2)							
		END	
	ELSE	
		BEGIN
			SET @RETORNO = SUBSTRING(@DOCUMENTO,1,2) + '.' + SUBSTRING(@DOCUMENTO,3,3) + '.' + SUBSTRING(@DOCUMENTO,6,3) + '/' + SUBSTRING(@DOCUMENTO,9,4) + '-' + SUBSTRING(@DOCUMENTO,12,2)				
		END	--						25.575.633/0001-01
	

RETURN @RETORNO
END

SELECT 
ID_CLIENTE,
NOME,
DOCUMENTO,
dbo.FormataCPF(DOCUMENTO,TIPO_PESSOA) AS CPF_CNPJ
FROM CLIENTES