--EXCLUINDO UMA FUNCAO
CREATE FUNCTION dbo.CalculaDescontooo(@DESCONTO NUMERIC(12,2))
RETURNS NUMERIC(18,2)
AS
BEGIN
    DECLARE @VALOR_COM_DESCONTO		NUMERIC(18,2)	

	SELECT @VALOR_COM_DESCONTO = A.VALOR_UNITARIO - (A.VALOR_UNITARIO * @DESCONTO / 100)
	FROM PRODUTOS A(NOLOCK)    
	
    
	RETURN @VALOR_COM_DESCONTO
END


--PARA EXCLUIR A FUNÇÃO SIMPLESMENTE UTILIZAMOS O COMANDO DROP FUNCTION
DROP FUNCTION dbo.CalculaDescontooo

