USE CURSO
GO

--FAZENDO A CONSULTA ATRAVÉS DO SELECT
SELECT 
A.ID_PEDIDO,
A.DATA_PEDIDO,
A.DATA_ENTREGA,
B.NOME AS CLIENTE,
C.DESCRICAO AS PRODUTO,
C.VALOR_UNITARIO,
A.QUANTIDADE,
A.VALOR_TOTAL
FROM PEDIDOS A(NOLOCK)
INNER JOIN CLIENTES B(NOLOCK) ON (B.ID_CLIENTE=A.ID_CLIENTE)
INNER JOIN PRODUTOS C(NOLOCK) ON (C.ID_PRODUTO=A.ID_PRODUTO)



--CRIANDO UMA PROCEDURE SIMPLES DE CONSULTA
CREATE PROCEDURE SP_CONSULTA_PEDIDOS
AS
SELECT 
A.ID_PEDIDO,
A.DATA_PEDIDO,
A.DATA_ENTREGA,
B.NOME AS CLIENTE,
C.DESCRICAO AS PRODUTO,
C.VALOR_UNITARIO,
A.QUANTIDADE,
A.VALOR_TOTAL
FROM PEDIDOS A(NOLOCK)
INNER JOIN CLIENTES B(NOLOCK) ON (B.ID_CLIENTE=A.ID_CLIENTE)
INNER JOIN PRODUTOS C(NOLOCK) ON (C.ID_PRODUTO=A.ID_PRODUTO)
GO



EXEC SP_CONSULTA_PEDIDOS



--CRIANDO UMA PROCEDURE PARA INSERIR UM PRODUTO
CREATE PROCEDURE SP_CADASTRA_PRODUTO
AS
INSERT INTO PRODUTOS VALUES ('PAPEL DE PRESENTE',5.00)
GO

EXEC SP_CADASTRA_PRODUTO

SELECT * FROM PRODUTOS



--CRIANDO UMA PROCEDURE PARA ATUALIZAR UM PRODUTO
CREATE PROCEDURE SP_ATUALIZA_PRODUTO
AS
	UPDATE PRODUTOS SET VALOR_UNITARIO = 6.50 WHERE ID_PRODUTO = 25

GO


EXEC SP_ATUALIZA_PRODUTO

SELECT * FROM PRODUTOS




CREATE PROCEDURE SP_EXCLUI_PRODUTO
AS
	DELETE FROM PRODUTOS WHERE ID_PRODUTO = 25

GO


EXEC SP_EXCLUI_PRODUTO

SELECT * FROM PRODUTOS
