--CRIANDO UMA PROCEDURE PARA CONSULTAR PEDIDOS COM PARAMETRO DE DATA INICIAL E FINAL DO PEDIDO
CREATE PROCEDURE SP_CONSULTA_PRODUTOS_POR_DATA
@DATA_INICIAL		DATE,
@DATA_FINAL			DATE	
AS
SELECT 
A.ID_PEDIDO,
CAST(A.DATA_PEDIDO AS DATE) AS DATA_PEDIDO,
A.DATA_ENTREGA,
B.NOME,
B.TIPO_PESSOA,
C.DESCRICAO AS PRODUTO,
C.VALOR_UNITARIO,
A.QUANTIDADE,
A.VALOR_TOTAL AS TOTAL_PEDIDO
FROM PEDIDOS A(NOLOCK)
INNER JOIN CLIENTES B(NOLOCK) ON (B.ID_CLIENTE=A.ID_CLIENTE)
INNER JOIN PRODUTOS C(NOLOCK) ON (C.ID_PRODUTO=A.ID_PRODUTO)
WHERE CAST(A.DATA_PEDIDO AS DATE) BETWEEN @DATA_INICIAL AND @DATA_FINAL
GO


--EXECUÇÃO DA PROCEDURE
EXEC SP_CONSULTA_PRODUTOS_POR_DATA '2023-01-05','2023-01-05'




--CRIANDO UMA PROCEDURE PARA CONSULTAR PEDIDOS FEITO POR UM DETERMINADO CLIENTE
CREATE PROCEDURE SP_CONSULTA_PRODUTOS_POR_CLIENTE
@DOCUMENTO			VARCHAR(20)
AS
SELECT 
A.ID_PEDIDO,
CAST(A.DATA_PEDIDO AS DATE) AS DATA_PEDIDO,
A.DATA_ENTREGA,
B.NOME,
dbo.FormataCPF(B.DOCUMENTO, b.TIPO_PESSOA) AS CPF_CNPJ,
B.TIPO_PESSOA,
C.DESCRICAO AS PRODUTO,
C.VALOR_UNITARIO,
A.QUANTIDADE,
A.VALOR_TOTAL AS TOTAL_PEDIDO
FROM PEDIDOS A(NOLOCK)
INNER JOIN CLIENTES B(NOLOCK) ON (B.ID_CLIENTE=A.ID_CLIENTE)
INNER JOIN PRODUTOS C(NOLOCK) ON (C.ID_PRODUTO=A.ID_PRODUTO)
WHERE B.DOCUMENTO = @DOCUMENTO
GO

SELECT * FROM CLIENTES

EXEC SP_CONSULTA_PRODUTOS_POR_CLIENTE '23325528809'



SELECT * FROM PRODUTOS

--CRIANDO UMA PROCEDURE PARA CADASTRAR PRODUTOS
CREATE PROCEDURE SP_CADASTRA_PRODUTOS
@DESCRICAO		VARCHAR(200),
@VALOR_UNITARIO	NUMERIC(12,2)
AS
INSERT INTO PRODUTOS VALUES (@DESCRICAO, @VALOR_UNITARIO)
GO

EXEC SP_CADASTRA_PRODUTOS 'PAPEL CREPOM',2.80

SELECT * FROM PRODUTOS

--CRIANDO UMA PROCEDURE PARA ATUALIZAR PRODUTOS
CREATE PROCEDURE SP_ATUALIZA_PRODUTOS
@ID_PRODUTO		INTEGER,
@DESCRICAO		VARCHAR(200),
@VALOR_UNITARIO	NUMERIC(12,2)
AS
UPDATE PRODUTOS SET DESCRICAO = @DESCRICAO, VALOR_UNITARIO = @VALOR_UNITARIO
WHERE ID_PRODUTO = @ID_PRODUTO
GO

EXEC SP_ATUALIZA_PRODUTOS 26, 'PAPEL TOALHA', 23.50 


SELECT * FROM PRODUTOS




--CRIANDO UMA PROCEDURE PARA EXCLUIR PRODUTOS
CREATE PROCEDURE SP_EXCLUI_PRODUTOS
@ID_PRODUTO		INTEGER
AS
DELETE FROM PRODUTOS WHERE ID_PRODUTO = @ID_PRODUTO
GO

EXEC SP_EXCLUI_PRODUTOS 26


SELECT * FROM PRODUTOS



