--CRIANDO UMA PROCEDURE PARA CONSULTAR PEDIDOS EM GERAL PORÉM PASSAREMOS PARAMETROS
CREATE PROCEDURE SP_CONSULTA_PEDIDOS_TODOS
@DATA_INICIAL		DATE,
@DATA_FINAL			DATE	
AS
SELECT 
A.ID_PEDIDO,
CAST(A.DATA_PEDIDO AS DATE) AS DATA_PEDIDO,
A.DATA_ENTREGA,
B.NOME,
B.TIPO_PESSOA,
C.DESCRICAO AS PRODUTO,
C.VALOR_UNITARIO,
A.QUANTIDADE,
A.VALOR_TOTAL AS TOTAL_PEDIDO
FROM PEDIDOS A(NOLOCK)
INNER JOIN CLIENTES B(NOLOCK) ON (B.ID_CLIENTE=A.ID_CLIENTE)
INNER JOIN PRODUTOS C(NOLOCK) ON (C.ID_PRODUTO=A.ID_PRODUTO)
WHERE CAST(A.DATA_PEDIDO AS DATE) BETWEEN @DATA_INICIAL AND @DATA_FINAL
GO


--PODEMOS SIMPLESMENTE ALTERAR A PROCEDURE
--CRIAMOS UMA PROCEDURE PARA CONSULTAR PEDIDOS EM GERAL, PORÉM CRIAMOS A PROC COM PARAMETROS E AGORA NÃO QUEREMOS MAIS ISSO
ALTER PROCEDURE SP_CONSULTA_PEDIDOS_TODOS
AS
SELECT 
A.ID_PEDIDO,
CAST(A.DATA_PEDIDO AS DATE) AS DATA_PEDIDO,
A.DATA_ENTREGA,
B.NOME,
B.TIPO_PESSOA,
C.DESCRICAO AS PRODUTO,
C.VALOR_UNITARIO,
A.QUANTIDADE,
A.VALOR_TOTAL AS TOTAL_PEDIDO
FROM PEDIDOS A(NOLOCK)
INNER JOIN CLIENTES B(NOLOCK) ON (B.ID_CLIENTE=A.ID_CLIENTE)
INNER JOIN PRODUTOS C(NOLOCK) ON (C.ID_PRODUTO=A.ID_PRODUTO)
GO

EXEC SP_CONSULTA_PEDIDOS_TODOS