--PARA EXCLUIR UMA PROCEDURE BASTA UTILIZAR APENAS O COMANDO DROP + O NOME DA PROCEDURE
CREATE PROCEDURE SP_CONSULTA_CLIENTES
AS
SELECT 
A.NOME,
A.TIPO_PESSOA,
A.DOCUMENTO
FROM CLIENTES A(NOLOCK)
GO

EXEC SP_CONSULTA_CLIENTES

DROP PROCEDURE SP_CONSULTA_CLIENTES

--AGORA SE JÁ EXECUTARMOS ESSA PROCEDURE NÃO EXISTE MAIS
EXEC SP_CONSULTA_CLIENTES