--COMANDO IF É UMA ESTRUTURA CONDICIONAL
--COMANDO IF SIGNIFICA *** SE ***



DECLARE @PRIMEIRO_NUMERO		INTEGER
SET @PRIMEIRO_NUMERO = 7
--PRINT @PRIMEIRO_NUMERO

IF @PRIMEIRO_NUMERO > 5	
		PRINT 'O número é maior que 5'
		
--------------------------------------------

DECLARE @SEGUNDO_NUMERO		INTEGER
SET @SEGUNDO_NUMERO = 5

IF @SEGUNDO_NUMERO > 5	
		PRINT 'O número é maior que 5'

---------------------------------------------
DECLARE @TERCEIRO_NUMERO		INTEGER
SET @TERCEIRO_NUMERO = 5

IF @TERCEIRO_NUMERO > 5	
	PRINT 'O número é MAIOR que 5'
ELSE
	PRINT 'O número é MENOR OU IGUAL que 5'


--VAMOS UTILIZAR O IF EM UM EXEMPLO PRATICO...NA CRIAÇÃO DE UMA FUNÇÃO
CREATE FUNCTION dbo.FormataDocCliente(@DOCUMENTO VARCHAR(14), @TIPO_PESSOA VARCHAR(01))
RETURNS VARCHAR(20)
AS
BEGIN
	
	DECLARE @RETORNO VARCHAR(20)
	
	IF @TIPO_PESSOA = 'F'
		
			SET @RETORNO = SUBSTRING(@DOCUMENTO,1,3) + '.' + SUBSTRING(@DOCUMENTO,4,3) + '.' + SUBSTRING(@DOCUMENTO,7,3) + '-' + SUBSTRING(@DOCUMENTO,10,2)							
		
	ELSE	
		
			SET @RETORNO = SUBSTRING(@DOCUMENTO,1,2) + '.' + SUBSTRING(@DOCUMENTO,3,3) + '.' + SUBSTRING(@DOCUMENTO,6,3) + '/' + SUBSTRING(@DOCUMENTO,9,4) + '-' + SUBSTRING(@DOCUMENTO,12,2)				
		
	

RETURN @RETORNO
END

	
	
SELECT 
ID_CLIENTE,
NOME,
dbo.FormataDocCliente(DOCUMENTO,TIPO_PESSOA) AS CPF_CNPJ
FROM CLIENTES