-- A IMPORTANCIA DO BEGIN E END JUNTO COM O IF
-- VAMOS UTILIZAR UMA MÉDIA FINAL 7 E UMA MÉDIA FINAL 5

DECLARE @MEDIA_FINAL	INTEGER
DECLARE @SITUACAO		VARCHAR(100)
DECLARE @MENSAGEM		VARCHAR(100)

SET @MEDIA_FINAL = 7
SET @SITUACAO = 'AGUARDANDO MÉDIA FINAL'
SET @MENSAGEM = 'MENSAGEM SERÁ APROVADO OU REPROVADO DE ACORDO COM A MÉDIA'

IF @MEDIA_FINAL >= 7	
	SET @SITUACAO = 'APROVADO'
	SET @MENSAGEM = 'PARABÉNS, VOCÊ PASSOU DE ANO'


PRINT @SITUACAO
PRINT @MENSAGEM


-- CRIANDO A ESTRUTURA CONDICIONAL CORRETA COM O BEGIN E END
DECLARE @MEDIA_FINAL_B	INTEGER
DECLARE @SITUACAO_B		VARCHAR(100)
DECLARE @MENSAGEM_B		VARCHAR(100)

SET @MEDIA_FINAL_B = 4
SET @SITUACAO_B = 'AGUARDANDO MÉDIA FINAL'
SET @MENSAGEM_B = 'MENSAGEM SERÁ APROVADO OU REPROVADO DE ACORDO COM A MÉDIA'

IF @MEDIA_FINAL_B >= 7	
	BEGIN
		SET @SITUACAO_B = 'APROVADO'
		SET @MENSAGEM_B = 'PARABÉNS, VOCÊ PASSOU DE ANO'
	END
ELSE
	BEGIN
		SET @SITUACAO_B = 'REPROVADO'
		SET @MENSAGEM_B = 'CUIDADO, VOCÊ ESTÁ DE RECUPERAÇÃO'
	END

PRINT @SITUACAO_B
PRINT @MENSAGEM_B

-- NA PROXIMA AULA VAMOS APRENDER SOBRE LOOP WHILE E COLOCAR O IF BEGIN END EM PRATICA COM O LOOP WHILE

