--O COMANDO WHILE SIGNIFICA ENQUANTO E SERVE PARA SER UTILIZADO COMO UMA ESTRUTURA DE REPETIÇÃO
--PODEMOS FAZER UMA DETERMINADA AÇÃO ATÉ QUE UMA CONDIÇÃO SEJA SATISFATÓRIA
--VAMOS AOS EXEMPLOS PRÁTICOS

DECLARE @CONTADOR	INTEGER
SET @CONTADOR = 1

WHILE @CONTADOR <= 5
	BEGIN
		PRINT @CONTADOR
		SET @CONTADOR = @CONTADOR + 1
	END



--CONTAGEM REGRESSIVA
DECLARE @CONTADOR_REGRESSIVO	INTEGER
SET @CONTADOR_REGRESSIVO = 10

WHILE @CONTADOR_REGRESSIVO > 0
	BEGIN
		PRINT 'Contador número ' + cast(@CONTADOR_REGRESSIVO as varchar)
		SET @CONTADOR_REGRESSIVO = @CONTADOR_REGRESSIVO - 1
	END



--VERIFICAÇÕES DE DATA
DECLARE @DATA_LIMITE	DATE
DECLARE @DATA_ATUAL		DATE

SET @DATA_LIMITE = '2024-11-01'

SET @DATA_ATUAL		= '2024-11-01'

--PRINT EOMONTH(@DATA_LIMITE)

WHILE @DATA_ATUAL <> EOMONTH(@DATA_LIMITE)
	BEGIN
		PRINT 'Hoje é dia: ' + CONVERT(VARCHAR(10),@DATA_ATUAL,103)
		SET @DATA_ATUAL = DATEADD(DAY,1,@DATA_ATUAL)		
	END


--PODEMOS UTILIZAR O LOOP WHILE EM DIVERSAS SITUAÇÕES, MAIS ADIANTE VEREMOS EXEMPLOS MAIS PRATICOS