USE CURSO
GO

-- CRIANDO UMA TABELA TEMPORÁRIA DE SESSÃO
CREATE TABLE #TEMP_PRODUTOS(
ID_PRODUTO		INTEGER IDENTITY(1,1) PRIMARY KEY,
DESCRICAO		VARCHAR(200),
VALOR_UNITARIO	NUMERIC(18,2))
GO


INSERT INTO #TEMP_PRODUTOS VALUES ('SABONETE',8.00)
INSERT INTO #TEMP_PRODUTOS VALUES ('CREME DENTAL',12.00)

SELECT * FROM #TEMP_PRODUTOS

DROP TABLE #TEMP_PRODUTOS




--CRIANDO UMA TABELA TEMPORARIA GLOBAL
CREATE TABLE ##TEMP_PRODUTOS(
ID_PRODUTO		INTEGER IDENTITY(1,1) PRIMARY KEY,
DESCRICAO		VARCHAR(200),
VALOR_UNITARIO	NUMERIC(18,2))
GO


INSERT INTO ##TEMP_PRODUTOS VALUES ('SABONETE',8.00)
INSERT INTO ##TEMP_PRODUTOS VALUES ('CREME DENTAL',12.00)

SELECT * FROM ##TEMP_PRODUTOS

DROP TABLE ##TEMP_PRODUTOS