--VAMOS DELETAR UM PRODUTO PARA TESTAR UMA CONSTRAINT
SELECT * FROM PEDIDOS where ID_PRODUTO = 3

DELETE FROM PRODUTOS WHERE ID_PRODUTO = 1




--PRODUTOS QUE NÃO EXISTEM NA TABELA PEDIDOS
SELECT * FROM PRODUTOS A(NOLOCK)
WHERE NOT EXISTS (SELECT 1 FROM PEDIDOS B(NOLOCK)
					WHERE B.ID_PRODUTO = A.ID_PRODUTO)


DELETE FROM PRODUTOS WHERE ID_PRODUTO = 3