--UTILIZANDO TRIGGER PARA MONITORAR NOSSO BANCO DE DADOS

CREATE TABLE LOGS_PEDIDOS (
ID_LOG				INTEGER	IDENTITY(1,1),
DATA_HORA_LOG		DATETIME,
ID_PEDIDO			INTEGER,
ID_PRODUTO			INTEGER,
ID_CLIENTE			INTEGER,
TOTAL_VENDA			NUMERIC(18,2),
DESCRICAO			VARCHAR(200))
GO


--CRIANDO UMA TRIGGER PARA INSERIR LOGS APÓS INSERÇÃO DE DADOS
CREATE TRIGGER TR_REGISTRA_LOG_PEDIDOS
ON PEDIDOS
FOR INSERT
AS
BEGIN
	DECLARE @ID_PEDIDO		INTEGER
	DECLARE @ID_CLIENTE		INTEGER
	DECLARE @ID_PRODUTO		INTEGER
	DECLARE @TOTAL_VENDA	NUMERIC(18,2)

	SELECT	@ID_PEDIDO		= ID_PEDIDO,
			@ID_CLIENTE		= ID_CLIENTE,
			@ID_PRODUTO		= ID_PRODUTO,
			@TOTAL_VENDA	= VALOR_TOTAL
			FROM INSERTED 	

	INSERT INTO LOGS_PEDIDOS VALUES(GETDATE(), @ID_PEDIDO, @ID_PRODUTO, @ID_CLIENTE, @TOTAL_VENDA, 'Pedido realizado via sistema')
END
GO


SELECT * FROM LOGS_PEDIDOS


--VAMOS INSERIR UM PEDIDO PARA VER O FUNCIONAMENTO DA TRIGGER
INSERT INTO PEDIDOS VALUES (1,1,'2023-01-07','2023-01-15',5,100.00)



INSERT INTO PEDIDOS VALUES (1,1,'2023-01-08','2023-01-15',5,100.00)



SELECT * FROM LOGS_PEDIDOS





--TRIGGER PARA MONITORAR EXCLUSÃO DE PRODUTOS
CREATE TRIGGER TR_PRODUTOS_EXCLUIDOS
ON PRODUTOS
FOR DELETE
AS
BEGIN
	
	DECLARE @ID_PRODUTO		INTEGER
	

	SELECT	@ID_PRODUTO		= ID_PRODUTO			
			FROM DELETED 	

	INSERT INTO LOGS_PEDIDOS VALUES(GETDATE(), 0, @ID_PRODUTO, 0, 0, 'Produto Excluído')
END
GO


DELETE FROM PRODUTOS WHERE ID_PRODUTO = 5

SELECT * FROM LOGS_PEDIDOS
	



--TRIGGER PARA MONITORAR ATUALIZAÇÃO DE CLIENTES
CREATE TRIGGER TR_CLIENTES_ATUALIZACAO_CADASTRO
ON CLIENTES
FOR UPDATE
AS
BEGIN
	
	DECLARE @ID_CLIENTE		INTEGER
	

	SELECT	@ID_CLIENTE		= ID_CLIENTE			
			FROM inserted 	

	INSERT INTO LOGS_PEDIDOS VALUES(GETDATE(), 0, 0, @ID_CLIENTE, 0, 'Cadastro do cliente atualizado')
END
GO


SELECT * FROM CLIENTES WHERE ID_CLIENTE = 1

UPDATE CLIENTES SET NOME = 'JEFFERSON NAVARAUSCKAS' WHERE ID_CLIENTE = 1

SELECT * FROM LOGS_PEDIDOS