--UTILIZANDO TRIGGER PARA MONITORAR NOSSO BANCO DE DADOS
CREATE TRIGGER TR_REGISTRA_LOG_PEDIDOS_TESTE
ON PEDIDOS
FOR INSERT
AS
BEGIN
	DECLARE @ID_PEDIDO		INTEGER
	DECLARE @ID_CLIENTE		INTEGER
	DECLARE @ID_PRODUTO		INTEGER
	DECLARE @TOTAL_VENDA	NUMERIC(18,2)

	SELECT	@ID_PEDIDO		= ID_PEDIDO,
			@ID_CLIENTE		= ID_CLIENTE,
			@ID_PRODUTO		= ID_PRODUTO,
			@TOTAL_VENDA	= VALOR_TOTAL
			FROM INSERTED 	

	INSERT INTO LOGS_PEDIDOS VALUES(GETDATE(), @ID_PEDIDO, @ID_PRODUTO, @ID_CLIENTE, @TOTAL_VENDA, 'Pedido realizado via sistema')
END
GO


--SIMPLESMENTE COM O COMANDO ALTER TRIGGER PODEMOS ALTERAR A TRIGGER
ALTER TRIGGER TR_REGISTRA_LOG_PEDIDOS_TESTE
ON PEDIDOS
FOR INSERT
AS
BEGIN
	DECLARE @ID_PEDIDO		INTEGER
	DECLARE @ID_CLIENTE		INTEGER
	DECLARE @ID_PRODUTO		INTEGER
	DECLARE @TOTAL_VENDA	NUMERIC(18,2)

	SELECT	@ID_PEDIDO		= ID_PEDIDO,
			@ID_CLIENTE		= ID_CLIENTE,
			@ID_PRODUTO		= ID_PRODUTO,
			@TOTAL_VENDA	= VALOR_TOTAL
			FROM INSERTED 	

	INSERT INTO LOGS_PEDIDOS VALUES(GETDATE(), @ID_PEDIDO, @ID_PRODUTO, @ID_CLIENTE, @TOTAL_VENDA, 'Pedido realizado')
END
GO


--COM O COMANDO DROP TRIGGER PODEMOS EXCLUIR A TRIGGER
DROP TRIGGER TR_REGISTRA_LOG_PEDIDOS_TESTE

