-- IMAGINA O SEGUINTE CENÁRIO: PRECISAMOS MEDIR O VALOR ACUMULADO DE VENDAS PARA CADA CLIENTE
-- ENTÃO TEMOS EM NOSSA TABELA O SEGUINTE

SELECT
A.ID_PEDIDO,
CONVERT(VARCHAR(10),A.DATA_PEDIDO,103) AS DATA_PEDIDO,
A.ID_PRODUTO,
B.DESCRICAO AS PRODUTO,
A.ID_CLIENTE,
C.NOME AS CLIENTE,
A.VALOR_TOTAL AS TOTAL_VENDA
FROM PEDIDOS A(NOLOCK)
INNER JOIN PRODUTOS B(NOLOCK) ON (B.ID_PRODUTO=A.ID_PRODUTO)
INNER JOIN CLIENTES C(NOLOCK) ON (C.ID_CLIENTE=A.ID_CLIENTE)
ORDER BY A.ID_CLIENTE



CREATE TABLE #PERFORMANCE_CLIENTE(
ID_PEDIDO						INTEGER,
DATA_PEDIDO						DATE,
ID_PRODUTO						INTEGER,
PRODUTO							VARCHAR(200),
ID_CLIENTE						INTEGER,
CLIENTE							VARCHAR(200),
TOTAL_VENDA						NUMERIC(18,2),
TOTAL_ACUMULADO_POR_VENDA		NUMERIC(18,2))
GO



--VAMOS CRIAR UM CURSOR-----------------------------------
DECLARE @ID_PEDIDO				INTEGER
DECLARE @ID_CLIENTE				INTEGER
DECLARE @ID_CLIENTE_CONTROLE	INTEGER
DECLARE @TOTAL_VENDA			INTEGER
DECLARE @TOTAL_ACUMULADO		NUMERIC(18,2)


SET @TOTAL_ACUMULADO = 0
SET @ID_CLIENTE_CONTROLE = (SELECT MIN(ID_CLIENTE) FROM PEDIDOS(NOLOCK))


DECLARE CURSOR_PERFORMANCE CURSOR FOR
SELECT
A.ID_PEDIDO,
A.ID_CLIENTE,
A.VALOR_TOTAL
FROM PEDIDOS A(NOLOCK)
INNER JOIN PRODUTOS B(NOLOCK) ON (B.ID_PRODUTO=A.ID_PRODUTO)
INNER JOIN CLIENTES C(NOLOCK) ON (C.ID_CLIENTE=A.ID_CLIENTE)
ORDER BY A.ID_CLIENTE

OPEN CURSOR_PERFORMANCE 
FETCH NEXT FROM CURSOR_PERFORMANCE INTO @ID_PEDIDO, @ID_CLIENTE, @TOTAL_VENDA

WHILE @@FETCH_STATUS = 0 

	BEGIN

		IF @ID_CLIENTE_CONTROLE <> @ID_CLIENTE
			BEGIN
				SET @TOTAL_ACUMULADO = 0
			END

		
		SET @TOTAL_ACUMULADO = @TOTAL_ACUMULADO + @TOTAL_VENDA

		INSERT INTO #PERFORMANCE_CLIENTE
		SELECT 
		A.ID_PEDIDO,
		CONVERT(VARCHAR(10),A.DATA_PEDIDO,103) AS DATA_PEDIDO,
		A.ID_PRODUTO,
		B.DESCRICAO AS PRODUTO,
		A.ID_CLIENTE,
		C.NOME AS CLIENTE,
		A.VALOR_TOTAL AS TOTAL_VENDA,
		@TOTAL_ACUMULADO
		FROM PEDIDOS A(NOLOCK)
		INNER JOIN PRODUTOS B(NOLOCK) ON (B.ID_PRODUTO=A.ID_PRODUTO)
		INNER JOIN CLIENTES C(NOLOCK) ON (C.ID_CLIENTE=A.ID_CLIENTE)
		WHERE A.ID_PEDIDO = @ID_PEDIDO
		AND A.ID_CLIENTE = @ID_CLIENTE

		SET @ID_CLIENTE_CONTROLE = @ID_CLIENTE

	

FETCH NEXT FROM CURSOR_PERFORMANCE INTO @ID_PEDIDO, @ID_CLIENTE, @TOTAL_VENDA

END 

CLOSE CURSOR_PERFORMANCE  
DEALLOCATE CURSOR_PERFORMANCE 



SELECT * FROM #PERFORMANCE_CLIENTE
