-- IMAGINA O SEGUINTE CENÁRIO: PRECISAMOS EXCLUIR PEDIDOS QUE TENHAM UM TOTAL ACUMULADO DE PERFORMANCE INFERIR A 500.00
-- ENTÃO TEMOS EM NOSSA TABELA O SEGUINTE

SELECT * FROM PERFORMANCE_CLIENTE
WHERE TOTAL_ACUMULADO_POR_VENDA < 500


--VAMOS CRIAR UM CURSOR PARA EXCLUIR PEDIDOS QUE TENHAM UM TOTAL ACUMULADO DE PERFORMANCE INFERIOR A 500.00
DECLARE @ID_PEDIDO				INTEGER


DECLARE CURSOR_EXCLUSAO CURSOR FOR
SELECT
ID_PEDIDO
FROM PERFORMANCE_CLIENTE
WHERE TOTAL_ACUMULADO_POR_VENDA < 500

OPEN CURSOR_EXCLUSAO 
FETCH NEXT FROM CURSOR_EXCLUSAO INTO @ID_PEDIDO

WHILE @@FETCH_STATUS = 0 

	BEGIN		

		DELETE PERFORMANCE_CLIENTE WHERE ID_PEDIDO = @ID_PEDIDO			

	

FETCH NEXT FROM CURSOR_EXCLUSAO INTO @ID_PEDIDO

END 

CLOSE CURSOR_EXCLUSAO  
DEALLOCATE CURSOR_EXCLUSAO 



SELECT * FROM PERFORMANCE_CLIENTE
WHERE TOTAL_ACUMULADO_POR_VENDA < 500


