--O SYS.OBJECTS É UMA TABELA DE SISTEMA (SYSTEM) QUE GRAVA TODOS OS OBJETOS CONTIDOS NO BANCO DE DADOS (OBJECTS)

SELECT * FROM SYS.objects


--ATRAVES DELES PODEMOS VER TODAS TABELAS CRIADOS POR USUARIOS NO BANCO DE DADOS, PROCEDURES, FUNCOES, VIEWS, TRIGGERS E TABLEAS DE SISTEMAS

--VERIFICANDO AS TABELAS DE SISTEMA --TABELAS DO PROPRIO SQL SERVER
SELECT * FROM SYS.objects WHERE TYPE = 'S'



--VERIFICANDO AS TABELAS CRIADAS POR USUÁRIOS
SELECT * FROM SYS.objects WHERE TYPE = 'U'


--VERIFICANDO AS PROCEDURES
SELECT * FROM SYS.objects WHERE TYPE = 'P' --AND NAME LIKE '%PEDIDOS%'


--VERIFICANDO AS FUNCOES
SELECT * FROM SYS.objects WHERE TYPE = 'FN'

--VERIFICANDO AS VIEWS
SELECT * FROM SYS.objects WHERE TYPE = 'V'

--VERIFICANDO AS TRIGGERS
SELECT * FROM SYS.objects WHERE TYPE = 'TR'


--TAMBÉM PODEMOS PROCURAR UM OBJETO POR NOME
SELECT * FROM SYS.OBJECTS WHERE NAME LIKE '%PRODU%'
