--O COMANDO SP_HELPTEXT É UTILIZADO PARA ABRIR OS OBJETOS COMO PROCEDURES, FUNCOES E TRIGGERS

SELECT * FROM SYS.OBJECTS WHERE TYPE IN ('FN','TR','V','P')

SP_HELPTEXT CalculaDesconto


SP_HELPTEXT SP_CONSULTA_PEDIDOS


SP_HELPTEXT TR_REGISTRA_LOG_PEDIDOS


SP_HELPTEXT VW_PEDIDOS


