--SCHEMAS: OS SCHEMAS NO SQL SERVER SÃO UM TIPO DE "RECIPIENTE" QUE É UTILIZADO PARA SEPARAR OS OBJETOS E MANTER OS OBJETOS DE FORMA MAIS ORGANIZADA
--POR EXEMPLO: TUDO QUE CRIAMOS SE NÃO DECLARARMOS UM SCHEMA O SQL SERVER CRIA AUTOMATICAMENTE NO SCHEMA CHAMADO DBO


--OBSERVE ALGUNS OBJETOS QUE CRIAMOS
SELECT 
A.name AS NOME_OBJETO,
A.type AS TIPO_OBJETO,
A.type_desc AS DESCRICAO_OBJETO,
B.schema_id AS ID_SCHEMA,
B.name AS NOME_SCHEMA
FROM SYS.OBJECTS A(NOLOCK)
INNER JOIN SYS.schemas B(NOLOCK) ON (B.schema_id = A.schema_id)
AND A.type IN ('U','P','V','FN')
ORDER BY A.type



--CRIANDO UM SCHEMA
CREATE SCHEMA TST


--CRIANDO UMA TABELA DENTRO DO SCHEMA CRIADO

CREATE TABLE TST.TABELA_TESTE(
ID_TESTE		INTEGER,
DESCRICAO		VARCHAR(200))
GO



SELECT 
A.name AS NOME_OBJETO,
A.type AS TIPO_OBJETO,
A.type_desc AS DESCRICAO_OBJETO,
B.schema_id AS ID_SCHEMA,
B.name AS NOME_SCHEMA

FROM SYS.OBJECTS A(NOLOCK)
INNER JOIN SYS.schemas B(NOLOCK) ON (B.schema_id = A.schema_id)
AND A.type IN ('U','P','V','FN')
ORDER BY A.type


--PORÉM QUALQUER OPERAÇÃO QUE SEJA REALIZADA EM UM SCHEMA CRIADO PELO USUÁRIO É OBRIGATÓRIO SEMPRE APONTAR O SCHEMA

INSERT INTO TABELA_TESTE VALUES (1, 'TESTE')

INSERT INTO TST.TABELA_TESTE VALUES (1, 'TESTE')




SELECT * FROM TABELA_TESTE

SELECT * FROM TST.TABELA_TESTE

