USE [master]
GO

/****** Object:  Database [CURSO_BKP]    Script Date: 04/12/2023 11:08:57 ******/
CREATE DATABASE [CURSO_BKP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CURSO_BKP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CURSO_BKP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CURSO_BKP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CURSO_BKP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CURSO_BKP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CURSO_BKP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CURSO_BKP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CURSO_BKP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CURSO_BKP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CURSO_BKP] SET ARITHABORT OFF 
GO

ALTER DATABASE [CURSO_BKP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CURSO_BKP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CURSO_BKP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CURSO_BKP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CURSO_BKP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CURSO_BKP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CURSO_BKP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CURSO_BKP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CURSO_BKP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CURSO_BKP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CURSO_BKP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CURSO_BKP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CURSO_BKP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CURSO_BKP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CURSO_BKP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CURSO_BKP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CURSO_BKP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CURSO_BKP] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CURSO_BKP] SET  MULTI_USER 
GO

ALTER DATABASE [CURSO_BKP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CURSO_BKP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CURSO_BKP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CURSO_BKP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CURSO_BKP] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CURSO_BKP] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CURSO_BKP] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CURSO_BKP] SET  READ_WRITE 
GO


