USE CURSO_BKP
GO

--CRIANDO TABELA DE PRODUTOS
IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'PRODUTOS' AND TYPE = 'U')
	BEGIN
		DROP TABLE PRODUTOS
	END
GO

CREATE TABLE PRODUTOS(
ID_PRODUTO		INTEGER IDENTITY(1,1) PRIMARY KEY,
DESCRICAO		VARCHAR(200),
VALOR_UNITARIOO	NUMERIC(18,2))
GO


CREATE INDEX IDX_ID_PRODUTO ON PRODUTOS(ID_PRODUTO)
GO


--CRIANDO TABELA DE CLIENTES
IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'CLIENTES' AND TYPE = 'U')
	BEGIN
		DROP TABLE CLIENTES
	END
GO

CREATE TABLE CLIENTES(
ID_CLIENTE		INTEGER IDENTITY(1,1) PRIMARY KEY,
NOME			VARCHAR(200),
TIPO_PESSOA		VARCHAR(01), 
DOCUMENTO		VARCHAR(14))
GO

CREATE INDEX IDX_ID_CLIENTE ON CLIENTES(ID_CLIENTE)
GO