/*ALTERANDO E EXCLUINDO INDICES*/

/*
COMANDO SP_HELP É UTILIZADO PARA VIZUALIZAR TODA ESTRUTURA DA TABELA
COMANDO DROP INDEX É USADO PARA EXCLUIR O INDICE DE UMA TABELA
COMANDO EXEC É UTILIZADO PARA EXECUTAR UM TRECHO DE CÓDIGO (EXEC É OPCIONAL)
*/

SP_HELP PRODUTOS

DROP INDEX PRODUTOS.IDX_ID_PR
GO

SP_HELP PRODUTOS

EXEC SP_RENAME N'PRODUTOS.IDX_ID_PROD', N'IDX_ID_PRODUTO', N'INDEX';
GO

SP_HELP PRODUTOS