/*ALTERANDO TABELAS*/
/*
COMANDO USE É UTILIZADO PARA SELECIONAR O BANCO DE DADOS A SER UTILIZADO
COMANDO ALTER TABLE É UTILIZADO PARA ALTERAR A ESTRUTURA DA TABELA
COMAND DROP COLUMN É UTILIZADO PARA EXCLUIR UMA COLUNA DA TABELA
COMANDO ADD É UTILIZADO PARA INCLUIR UM CAMPO EM UMA TABELA
COMANDO SP_RENAME É UTILIZADO PARA RENOMEAR O CAMPO DE UMA TABELA
*/

USE CURSO
GO

SELECT * FROM PRODUTOS -- SELECT COM * SOMENTE EM AMBIENTE DE TREINAMENTO E ESTUDOS.

ALTER TABLE PRODUTOS DROP COLUMN VALOR_UNITARIOO -- AQUI, DROPAMOS A COLUNA QUE QUEREMOS ALTERAR
GO

SELECT * FROM PRODUTOS

ALTER TABLE PRODUTOS ADD VALOR_UNIT NUMERIC(18,2) -- AQUI, ADICIONAMOS A NOVA COLUNA COM O CAMPO REAJUSTADO


SELECT * FROM PRODUTOS

SP_RENAME 'PRODUTOS.VALOR_UNIT', 'VALOR_UNITARIO' -- AQUI, RENOMEAMOS O NOME DA COLUNA

SELECT * FROM PRODUTOS