CREATE DATABASE CURSO
GO

USE CURSO
GO

-----------------------------------------------------------------------------------------------
/*TABELA CLIENTES*/

IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'CLIENTES' AND TYPE = 'U')
	BEGIN
		DROP TABLE CLIENTES
	END
GO

CREATE TABLE CLIENTES(
	ID_CLIENTE			INT PRIMARY KEY IDENTITY (1,1),
	NOME				VARCHAR(200),
	TIPO_PESSOA			VARCHAR(01),
	DOCUMENTO			VARCHAR(14)
);
GO

CREATE INDEX IDX_ID_CLIENTE ON CLIENTES(ID_CLIENTE)
GO

-----------------------------------------------------------------------------------------------
/*TABELA TIPO ENDEREÇO*/

IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'TIPO_ENDERECO' AND TYPE = 'U')
	BEGIN
		DROP TABLE TIPO_ENDERECO
	END
GO

CREATE TABLE TIPO_ENDERECO(
	ID_TIPO_ENDERECO	INT PRIMARY KEY IDENTITY(1,1),
	DESCRICAO			VARCHAR(200)
);
GO

-----------------------------------------------------------------------------------------------
/*TABELA ENDEREÇOS*/

IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'ENDERECOS' AND TYPE = 'U')
	BEGIN
		DROP TABLE ENDERECOS
	END
GO

CREATE TABLE ENDERECOS(
	ID_ENDERECO			INT PRIMARY KEY IDENTITY(1,1),
	LOGRADOURO			VARCHAR(200),
	COMPLEMENTO			VARCHAR(200),
	CEP					VARCHAR(10),
	CIDADE				VARCHAR(100),
	UF					VARCHAR(02),
	ID_TIPO_ENDERECO	INT FOREIGN KEY REFERENCES TIPO_ENDERECO(ID_TIPO_ENDERECO),
	ID_CLIENTE			INT FOREIGN KEY REFERENCES CLIENTES(ID_CLIENTE)
);
GO

CREATE INDEX IDX_ID_ENDERECOS ON ENDERECOS(ID_ENDERECO)
GO

-----------------------------------------------------------------------------------------------
/*TABELA TIPO TELEFONE*/

IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'TIPO_TELEFONE' AND TYPE = 'U')
	BEGIN
		DROP TABLE TIPO_TELEFONE
	END
GO

CREATE TABLE TIPO_TELEFONE(
	ID_TIPO_TELEFONE	INT PRIMARY KEY IDENTITY(1,1),
	DESCRICAO			VARCHAR(200)
);
GO

-----------------------------------------------------------------------------------------------
/*TABELA TELEFONES*/

IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'TELEFONES' AND TYPE = 'U')
	BEGIN
		DROP TABLE TELEFONES
	END
GO

CREATE TABLE TELEFONES(
	ID_TELEFONE			INT PRIMARY KEY IDENTITY(1,1),
	DDD					INT,
	TELEFONE			VARCHAR(20),
	ID_TIPO_TELEFONE	INT FOREIGN KEY REFERENCES TIPO_TELEFONE(ID_TIPO_TELEFONE),
	ID_CLIENTE			INT FOREIGN KEY REFERENCES CLIENTES(ID_CLIENTE)
);
GO

CREATE INDEX IDX_ID_TELEFONE ON TELEFONES(ID_TELEFONE)
GO

-----------------------------------------------------------------------------------------------
/*TABELA PRODUTOS*/

IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'PRODUTOS' AND TYPE = 'U')
	BEGIN
		DROP TABLE PRODUTOS
	END
GO

CREATE TABLE PRODUTOS(
	ID_PRODUTO			INT PRIMARY KEY IDENTITY(1,1),
	DESCRICAO			VARCHAR(200),
	VALOR_UNITARIOO		NUMERIC(18,2)
);
GO

CREATE INDEX IDX_ID_PR ON PRODUTOS(ID_PRODUTO)
GO

CREATE INDEX IDX_ID_PROD ON PRODUTOS(ID_PRODUTO)
GO

-----------------------------------------------------------------------------------------------
/*TABELA PEDIDOS*/

IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'PEDIDOS' AND TYPE = 'U')
	BEGIN
		DROP TABLE PEDIDOS
	END
GO

CREATE TABLE PEDIDOS(
	ID_PEDIDO			INT PRIMARY KEY IDENTITY(1,1),
	ID_CLIENTE			INT FOREIGN KEY REFERENCES CLIENTES(ID_CLIENTE),
	ID_PRODUTO			INT FOREIGN KEY REFERENCES PRODUTOS(ID_PRODUTO),
	DATA_PEDIDO			DATETIME,
	DATA_ENTREGA		DATE,
	QUANTIDADE			INT,
	VALOR_TOTAL			NUMERIC(18,2)
);
GO

CREATE INDEX IDX_ID_PEDIDO ON PEDIDOS(ID_PEDIDO)
GO

-----------------------------------------------------------------------------------------------
/*TABELA PEDIDOS TESTE*/

IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'PEDIDOS_TESTE' AND TYPE = 'U')
	BEGIN
		DROP TABLE PEDIDOS_TESTE
	END
GO

CREATE TABLE PEDIDOS_TESTE(
	ID_PEDIDO			INT PRIMARY KEY IDENTITY(1,1),
	ID_CLIENTE			INT FOREIGN KEY REFERENCES CLIENTES(ID_CLIENTE),
	ID_PRODUTO			INT FOREIGN KEY REFERENCES PRODUTOS(ID_PRODUTO),
	DATA_PEDIDO			DATETIME,
	DATA_ENTREGA		DATE,
	QUANTIDADE			INT,
	VALOR_TOTAL			NUMERIC(18,2)
);
GO