-- UPDATE SIMPLES

SELECT * FROM CLIENTES

UPDATE CLIENTES SET NOME = 'JOAQUIN DA SILVA SANTOS' WHERE ID_CLIENTE = 1;

UPDATE CLIENTES SET NOME = 'JOÃO DA SILVA RODRIGUES' WHERE ID_CLIENTE = 2;

SELECT * FROM PRODUTOS

UPDATE PRODUTOS SET DESCRICAO = 'BERMUDA' WHERE ID_PRODUTO = 2;

UPDATE PRODUTOS SET DESCRICAO = 'MEIA SOCIAL' WHERE ID_PRODUTO = 7;
