-- ATUALIZANDO REGISTROS NAS TABELAS COM INNER JOIN

-- LEMBRETE.: EXEMPLO DE UPDATE SIMPLES
SELECT * FROM PRODUTOS

UPDATE PRODUTOS SET DESCRICAO = 'BERMUDA' WHERE ID_PRODUTO = 2;
UPDATE PRODUTOS SET DESCRICAO = 'MEIA SOCIAL' WHERE ID_PRODUTO = 7;

SELECT * FROM CLIENTES

-- UPDATE COM INNER JOIN
SELECT * FROM TELEFONES TE 
	INNER JOIN TIPO_TELEFONE TI (NOLOCK) ON (TI.ID_TIPO_TELEFONE = TE.ID_TIPO_TELEFONE)
	INNER JOIN CLIENTES CL (NOLOCK) ON (CL.ID_CLIENTE = TE.ID_CLIENTE)
WHERE CL.NOME = 'JOAQUIN DA SILVA SANTOS'
	AND TI.DESCRICAO = 'CELULAR'


UPDATE TE SET DDD = 11
FROM TELEFONES TE
	INNER JOIN TIPO_TELEFONE TI (NOLOCK) ON (TI.ID_TIPO_TELEFONE = TE.ID_TIPO_TELEFONE)
	INNER JOIN CLIENTES CL (NOLOCK) ON (CL.ID_CLIENTE = TE.ID_CLIENTE)
WHERE CL.NOME = 'JOAQUIN DA SILVA SANTOS'
	AND TI.DESCRICAO = 'CELULAR'